version: 2
updates:
  - package-ecosystem: "npm" # or "pip", "maven", etc.
    directory: "/client" # location of the package files
    schedule:
      interval: "monthly"
  - package-ecosystem: "cargo"
    directory: "/server"
    schedule:
      interval: "monthly"
